export enum Rutas {
	ACCESS_DENIED = 'sin-acceso',
	RUTA_BASE_PORTAL = 'portal',
	NOT_FOUND = 'pagina-no-encontrada',
	HOME = '',
	TU_INFORMACION = 'tu-informacion',
	CITA_MEDICA = 'cita-medica',
	ATENCION_VIRTUAL_SALUD = 'avs',
	AYUDAS_DIAGNOSTICAS = 'ayudas-diagnosticas',
	RECLAMACION_SALUD = 'reclamacion-salud',
	AUTORIZACIONES = 'autorizaciones',
	MOVILIDAD = 'movilidad',
	BENEFICIARIO = 'beneficiario',
	RECLAMACIONES = 'reclamaciones',
	HOGAR = 'hogar',
	MEDIO_PAGO = 'medio-pago',
	BOLSILLO_SURA = 'bolsillo-sura',
	PAGO_EN_LINEA = 'pago-en-linea',
	CERTIFICADOS = 'certificados',
	DATOS_SALUD = 'datossalud',
	RECLAMACIONES_REEMBOLSOS = 'reclamaciones-reembolsos',
	PRE_REGISTRO = 'preregistro',
	OTROS_TRAMITES_EPS = 'otros-tramites-eps',
	AUTORIZACIONES_EPS = 'autorizaciones-eps',
	MEDICAMENTOS_EPS = 'medicamentos-eps',
	HISTORIA_CLINICA = 'historia-clinica',
}
