export enum WebComponents {
	HOME = 'wc-home',
	PERFIL_USUARIO = 'wc-perfil-usuario',
	CITA_MEDICA = 'wc-cita-medica',
	BOLSILLO_SURA = 'wc-bolsillo-sura',
	PRE_REGISTRO = 'wc-prerregistro-datos-cliente-salud',
	HADA = 'wc-hada',
	AYUDAS_DIAGNOSTICAS = 'wc-ayudas-diagnosticas',
	ATENCION_VIRTUAL_SALUD = 'wc-avs',
	RECLAMACION_SALUD = 'wc-reclamacion-salud',
	BENEFICIARIO = 'wc-beneficiario',
	RECLAMACIONES = 'wc-reclamaciones',
	CERTIFICADOS = 'wc-certificados',
	MEDIO_PAGO = 'wc-medio-pago',
	PAGO_EN_LINEA = 'wc-pago-en-linea',
	DATOS_SALUD = 'wc-datos-salud',
	SINIESTRO_INTEGRAL = 'wc-siniestro-integral',
	HISTORIA_CLINICA = 'wc-historia-clinica',
}
