export const LIST_ICON_MENU: Record<string, any> = {
	default: 'far fa-folder-minus',
	home: 'fal fa-th-large',
	hogar: 'fal fa-home',
	movilidad: 'fal fa-tire',
	salud: 'fal fa-stethoscope',
	citamedica: 'fal fa-file-medical',
	atencionvirtualsalud: 'fal fa-comment-alt-medical',
	autorizaciones: 'fal fa-file-medical-alt',
	ayudasdiagnosticas: 'fal fa-vials',
	reclamacionsalud: 'fa-envelope-open-dollar fal',
	vida: 'fal fa-heart',
	beneficiario: 'fal fa-user-plus',
	reclamaciones: 'fa-file-import fal',
	pagos: 'far fa-wallet',
	mediopago: 'fal fa-piggy-bank',
	bolsillo: 'fal fa-file-invoice-dollar',
	pagoenlinea: 'fal fa-envelope-open-dollar',
	certificados: 'fal fa-file-certificate',
	datossalud: 'fal fa-folder-medical',
	reclamacionesreembolsos: 'fa-light fa-handshake-simple mr-2',
	otrostramiteseps: 'fal fa-notes-medical',
	autorizacioneseps: 'fal fa-house-medical-circle-check',
	medicamentoseps: 'fal fa-suitcase-medical',
	historiaclinica: 'far fa-clipboard-medical',
};
